### ISSUE TITLE
Sads: dropzone doesn't work after starting video

### ISSUE THREAD

**Issue by xdumaine** [alishalisha/ilooklikeanengineer#2]
For the video rendering, I overwrite `model.background` which has all the image handling stuff. This was to reduce having to have extra logic for video in the other views, but we should keep a handle on the original background and restore it when droping an image, as well as killing the webcam stream to release the camera.

**Comment by alishalisha** [comment]
@xdumaine eek thanks for catching that! i am going to hide the dropzone like you had before as a hotfix :)
